name: mypy-check
on: [push]
jobs:
  check-mypy:
    runs-on: ubuntu-latest
    steps:
      - name: "mypy-check"
        uses: jpetrucciani/mypy-check@master
        with:
          path: "./myFM/myfm"
